== 5 Stacks and Queues
=== 5.1 Abstract Data Types

We refer to implementations of data types whose operations can be performed by users without knowledge of the underlying implementation.

=== 5.2 Stacks

A *stack* is a linear list where items are added and deleted from the same end. This means that stacks exhibit a "last in, first out" property. As an example, consider the following set of numbers:

[source]
----
36 15 52 23
----

If we want to print the following:
[source]
----
23 52 15 36
----

We would need to construct the following stack:
[source]
----
(top) 23 52 15 36 (bottom)
----

And we would remove numbers one at a time, printing them as we remove them. In psuedocode:
[source]
----
initialize empty stack S
read(num)
while a next number, num was read:
    push num onto S
    read(num)
while S is not empty:
    num = pop S
    print num
----

*5.2.1 Implementing a Stack Using an Array*

Stacks can be implemented with a struct containing an array and an int index of the top of the stack:

[source]
----
typedef struct {
    int top;
    int ST[MaxStack];
} StackType, *Stack;
----

Note that having StackType is useful for allocating a stack (general useful practice). When initialized, we'll set top to -1. Considering a stack variable, `Stack S`, we have access to `top` and the stack array, as we should based on our above definition of ADTs. Declaring a stack variable is therefore pretty simple:

[source]
----
Stack initStack(){
    Stack sp = malloc(sizeof(StackType));
    sp->top = -1;
    return sp;
}
----

And a user would simply initialize a new stack with `Stack S = initStack()`.

For our stack, we'll require three basic functions `isEmpty`, `pop`, and `push`. `isEmpty` is simple:

[source]
----
bool isEmpty(StackS){
    return (S->top == -1);
}
----

When we push items to the stack (after checking that the stack isn't full), we increment top (this works nicely because we we initialize top as -1) and set ST[top] to point to the item we're adding:

[source]
----
void push(Stack S, int n){
    if(S->top == MaxSize-1){
        printf("Stack overflow");
        exit(1);
    }
    ++(Stack->top);
    S->ST[S->top] = n;
}
----

To pop off the top of the stack (after checking that the stack isn't empty), we decrement top and return the value we just popped off:

[source]
----
int pop(Stack S){
    if(isEmpty(S)) return RogueVal; // designated value to indicate empty
    int temp = S->ST[S->top];
    --(S->top);
    return temp;
}
----

*Implementing a Stack Using a Linked List*

The array implementation is simple and efficient, but doesn't allow for resizing. One implementation that does is a linked list. We add new items to the head of the list, and remove the head when popping. The stack is defined as follows:

[source]
----
typedef struct node {
    int num;
    struct node *next;
} Node, *NodePtr;

typedef struct {
    NodePtr top;
} StackType, *Stack;
----

To initialize an new empty stack, we allocate memory for a stack `S` and set `S->top` to null. Checking if a stack is empty simply requires checking `S->top`:

[source]
----
bool isEmpty(Stack S){
    return (S->top == NULL);
}
----

Top push an object onto the top of the stack, we allocate memory and set the appropriate values:

[source]
----
void push(Stack S, int n){
    NodePtr np = malloc(sizeof(Node));
    np->num=n;
    np->next=S->top;
    S->top=np;
}
----

To pop the top object off the stack (after checking that there is a value to pop), we set `S->top` to the second item on the stack and return the value we are popping off.

[source]
----
int pop(Stack S){
    if(isEmpty(S)) return RogueVal; // Same as above
    NodePtr tmp = S->top;
    int temp = S->top->num;
    S->top = S->top->next;
    free(tmp);
    return temp;
}
----

Note: 5.3-5.5  omitted from notes

=== 5.6 Queues

A queue is a linear list where items are added to one end and removed from the other. The basic operations we want to perform on queues are:

* Adding an item to the queue (enqueue)
* Taking an item off the queue (dequeue)
* Checking if a queue is empty
* Examining the head of the queue

*Implementing a Queue Using an Array*

For implementations that use arrays, we need to know size at the time of allocation. In this discussion, `MaxQ` will be used to indicate this size. The data type is defined as follows:

[source]
----
typedef struct{
    int head,tail;
    int QA[MaxQ];
} QType, *Queue;
----

According to this definition, `head` and `tail` can vary between `0` and `MaxQ-1` (note that here, we are not filling index 0). We define the queue initialization function as follows:

[source]
----
Queue initQueue(){
    Queue qp = malloc(sizeof(QType));
    qp->head = qp->tail = 0;
    return qp;
}
----

We add things to the queue at the tail, incrementing tail and placing the object at the tail index. When implementing queues as arrays, the head will point "just in front" of the actual head, while the tail points directly to the last element. We enqueue as follows:

[source]
----
void enqueue(Queue Q, int n){
    if(Q->tail == MaxQ-1) Q->tail = 0;
    else ++(Q->tail);
    if(Q->tail == Q->head){
        printf("\nQueue is full\n");
        exit(1);
    }
    Q->QA[A->tail] = n;
}
----

Tail is either incremented, or set to 0 (so we can recognize the queue as full). If the queue is not full, the value is set at the new tail. Now, we consider dequeue:

[source]
----
int dequeue(Queue Q){
    if(isEmpty(Q)){
        printf("Attempted to remove from an empty queue\n");
        exit(1);
    }
    if(Q->head == MaxQ - 1) Q->head = 0;
    else ++(Q->head);
    return Q->QA[Q->head];
}
----

We first check first check if the queue is empty. If it is not, we increment the head and return the value of the item pointed to (this works nicely because, as mentioned earlier, head points one behind the actual head).

Consider the example sequence that illustrates usage of an array-implemented queue:

1) We insert the values 5 8 1 9 (where 5 is inserted first). Head is 0, tail is 4 (incremented 1 for each insertion).
2) We call dequeue, which returns 5. Head is incremented to 1.

*Implementing a Queue Using an Linked List*

As usual, the advantage of implementing with a linked list is that we don't have to know the size of our structure beforehand. Two pointers point to the first and last nodes in the queue struct (each node contains queue data and a pointer to the next). The typedefs thus look as follows:

[source]
----
// Generic implementation of queue data, only holding an int here
typedef struct{
    int num;
} QueueData;

typdef struct node{
    QueueData data;
    struct node *next;
} Node, *NodePtr;

typedef struct{
    NodePtr head,tail;
} QueueType, *Queue;
----

Queue initialization follows from this structure:

[source]
----
Queue initQueue(){
    Queue qp = malloc(sizeof(QueueType));
    qp->head=NULL;
    qp->tail=NULL;
    return qp;
}
----

Head and tail are both null in the initially empty queue. To check if a queue is null, we just need to check its head.

[source]
----
int empty(Queue Q){
    return (Q->head == NULL);
}
----

To `enqueue` objects, we first allocate space for their node. If the queue is empty, we set the head and tail to the new pointer. Otherwise, we set next pointer in the current tail to the new pointer and then set the new tail:

[source]
----
void enqueue(Queue Q, QueueData d){
    NodePtr np = malloc(sizeof(Node));
    np->data = d;
    np->next = NULL;
    if(isEmpty(Q)){
        Q->head = np;
        Q->tail = np;
    }
    else{
        Q->tail->next = np;
        Q->tail = np;
    }
}
----

When we dequeue, we first check that the queue is not empty. If it isn't, we store the `head` in a temporary variable (for later freeing) and increment `head` to `head->next`. If `head->next` is empty, we know the queue is now empty and set `Q->tail` to NULL. The data within the previous head node, which should be stored as soon as we know the queue isn't empty, is returned.

[source]
----
QueueData dequeue(Queue Q){
    if(isEmpty(Q)){
        printf("Tried to dequeue from an empty queue");
        exit(1);
    }
    QueueData hold = Q->head->data;
    NodePtr temp = Q->head;
    Q->head = Q->head->next;
    if(Q->head == NULL) Q->tail = NULL;
    free(temp);
    return hold;
}
----

