== 1 Sorting, Searching, and Merging

Note: Only two simple sorting algorithms, selection sort and insertion sort, are covered in this section.

=== 1.1. Sorting an Array: Selection Sort

Sorting involves arranging a set of values in ascending/descending order. We often find this desirable because many operations, like searching, can be done much more efficiently on sorted data.

We first consider selection sort. With this sorting method, we maintain separate sorted and unsorted portions of the list. In each iteration, we iterate over the unsorted part, fine the smallest number, and add it to the end of the sorted part. Example:

[source]
----
57 48 79 65 15 33 52
15 48 79 65 57 33 52 // 15 swaps with 57
15 33 79 54 57 48 52 // 33 swaps with 48
15 33 48 54 57 79 52 // 48 swaps with 79
15 33 48 52 57 79 54 // 52 swaps with 54
15 33 48 52 54 79 57 // 54 swaps with 57
15 33 48 52 54 57 79 // 79 swaps with 57
----

After this is complete, the array is completely sorted. Note that for an array of size 6, we made 5 passes. Selection sort passes over the array `n-1` time for an array of size `n`. This is because we need to pass over the full array one full time for each position except the last one, because by the time we reach it there is only one element remaining in the unsorted portion.

An implementation in C would look something like this:

[source]
----
void selectionSort(int list[], in lo, int hi){
// sorts list[lo] to list[hi]
    for(int h = lo, h < hi; ++h){
        int s = getSmallest(list,h,hi);
        swap(list,h,s);
    }
}
----

Where `swap` and `getSmallest` are implemented as follows:

[source]
----
int getSmallest(int list[], int lo, int hi){
// returns index of smallest value
    int smallest = lo;
    for(int h = lo; h < hi; ++h)
        if(list[h] > list[smallest])
            smallest = h;
    return smallest;
}

void swap(int list[], int i, int j){
    int temp = list[i];
    list[i] = list[j];
    list[j] = hold;
}
----

*Algorithm analysis: Selection Sort*

The number of comparisons we make decreases by 1 each pass. In the first pass, we make `n-1` comparisons, int he second we make `n-2`, etc. This series sums to `(1/2)(n)(n-1)`, which is on the order of `n^2`. Thus, we say that selection sort is of the order `O(n^2)`. Also, note that selection sort makes the same number of comparisons regardless of the data (so if it's input is already sorted, it makes no difference).

=== 1.2 Sorting an Array: Insertion Sort

Consider the same array as above. We can also sort it by iterating through the array, placing a number in the correct location within our sorted array at each step. In practice, this means iterating through the array, moving each index into the spot above and stopping once we've found the correct spot:

[source]
----
void insertionSort(int list[], int n){
// Sorts first n items (list[0]..list[n-1])
    for(int i = 1; i < n; ++i){
        int key = list[h];
        int k = h-1;
        while(k >= 0 && key < list[k]){
            list[k+1] = list[k];
            --k;
        }
        list[k+1] = key;
    }
}
----

We exit the while loop when `k` and assign the key to its final location when it is no longer less than the element before.

*Algorithm analysis: Insertion Sort*

For each item `j` we consider, we make between 1 and `j-1` comparisons. Therefore, on average we expect to make `(1/2)(j-1)` comparisons per item on random data. This results in a runtime on the order of `O(n^2)`. Note that performance can vary depending on the nature of the data; sorting requires `n-1` comparisons in the best case, `(1/4)n^2` on average, and `(1/2)n^2` in the worst case.

=== 1.3 Inserting an Element in Place

The pattern of inserting an element into a sorted (sub)list as we do in insertion sort is fairly common. We can abstract this idea into a function `insertInPlace`. We assume that the array has enough place to hold the new element.

[source]
----
void insertInPlace(int newItem, int list[], int m, int n){
// list[m..n] is sorted
// after insertion, list[m..n+1] will be sorted
    int k = n;
    while(k >= m && newItem < list[k]){
        list[k+1] = list[k];
        --k;
    }
    list[k+1] = newItem;
}
----

=== 1.6 Binary Search

Binary search is a fast searching method that relies upon the list being sorted. Throughout execution, we maintain a known subset where we know the element must exist, if it exists in the array. This contiguous space is called the _search space_, and we progress towards finding the element/termination by shrinking our search space in each iteration.

[source]
----
int binarySearch(int key, int list[], int lo, int hi){
    while(lo <= hi){
        int mid = (lo+hi)/2;
        if(key == list[mid]) return mid;
        if(key < list[mid]) hi = mid-1;
        else lo = mid+1;
    }
    return -1; // key wasn't found
}
----

=== 1.9 Merging Ordered Lists

Sorted lists can be merged by repeatedly taking the smallest head of the arrays being merged. This merging process can also be seen in _merge sort_.

[source]
----
int merge(int A[], int m, int B[], int n, int C[]){
    int i = 0, j = 0, k = -1;
    while(i < m && j < n){
        if(A[i] < B[j]) C[++k] = B[i++];
        else C[++k] = B[j++];
    }
    if(i == m)
        for( ; j < n; j++) C[++k] = B[j];
    else
        for( ; i < m; i++) C[++k] = A[i++];
    return m + n;
}
----

As long as we have more elements to process in both arrays, we enter the loop. When this is no longer the case, we insert all the extra elements from the larger array directly.

